storeapp/models.py
from . import db

class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(500), nullable=False)

    def __repr__(self):
        str = "ID: {}, Name: {}, Description: {}, Image: {} \n" 
        str = str.format(self.id, self.name, self.description, self.image)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('fruit_id',db.Integer,db.ForeignKey('fruits.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'fruit_id') )

class Fruit(db.Model):
    __tablename__ = 'fruits'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    
    def __repr__(self):
        str = "ID: {}, Name: {}, Description: {}, Image: {}, Price: {}, Category: {}\n" 
        str = str.format(self.id, self.name, self.description, self.image, self.price, self.category_id)
        return str

class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    address = db.Column(db.String(200))
    fruit = db.relationship("Fruit", secondary=orderdetails, backref="orders")
    total_cost = db.Column(db.Float)
    
    def __repr__(self):
        str = "ID: {}, Status: {}, Firstname: {}, Surname: {}, Email: {}, Phone: {}, Address: {}, Fruit: {}, Total Cost: {}\n" 
        str = str.format(self.id, self.status, self.firstname, self.surname, self.email, self.phone, self.address, self.fruit, self.total_cost)
        return str

storeapp/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    address = StringField("Your home address", validators=[InputRequired()])
    

storeapp/__init__.py
#import flask - from the package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
app = Flask(__name__)

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app.debug = True
    app.secret_key = 'THEbestPASSword123456789'
    
    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///fruitgarden.sqlite'

    #initialise db with flask app
    db.init_app(app)

    bootstrap = Bootstrap4(app)

   #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.main_bp)
    from . import admin
    app.register_blueprint(admin.admin_bp)
   
    return app

@app.errorhandler(404) 
# inbuilt function which takes error as parameter 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500) 
# inbuilt function which takes error as parameter 
def not_found(e): 
  return render_template("500.html")

storeapp/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Category, Fruit, Order
from .forms import CheckoutForm
from . import db


main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    category = Category.query.order_by(Category.name).all()
    return render_template('index.html', category = category)

@main_bp.route('/fruits/<int:categoryid>/')
def category_fruits(categoryid):
    fruits = Fruit.query.filter(Fruit.category_id==categoryid).all()
    return render_template('fruits.html', fruits = fruits)


@main_bp.route('/fruits/')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    fruits = Fruit.query.filter(Fruit.description.like(search)).all()
    return render_template('fruits.html', fruits = fruits)

# Referred to as "Basket" to the user
@main_bp.route('/order/', methods=['POST', 'GET'])
def order():
    fruit_id = request.values.get('fruit_id')

    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', surname='', email='', phone='', total_cost=0)
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed at creating a new order')
            order = None

    # calculate total price
    totalprice = 0
    if order is not None:
        for fruit in order.fruit:
            totalprice += fruit.price

    # are we adding an item?
    if fruit_id is not None and order is not None:
        fruit = Fruit.query.get(fruit_id)
        if fruit not in order.fruit:
            try:
                order.fruit.append(fruit)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your shopping cart'
            return redirect(url_for('main.order'))
        else:
            flash('Item already in shopping cart')
            return redirect(url_for('main.order'))
    return render_template('order.html', order=order, totalprice=totalprice)


# Delete specific basket items
@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        fruit_to_delete = Fruit.query.get(id)
        try:
            order.fruit.remove(fruit_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))

    
@main_bp.route('/checkout/', methods=['GET', 'POST'])
def checkout():
    form = CheckoutForm() 

    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        if form.validate_on_submit():
           order.status = True
           order.firstname = form.firstname.data
           order.surname = form.surname.data
           order.email = form.email.data
           order.phone = form.phone.data
           order.address = form.address.data
           total_cost = 0
        
           for fruit in order.fruit:
               total_cost = total_cost + fruit.price
           order.total_cost = total_cost
           try:
                db.session.commit()
                del session['order_id']
                flash('Thank you for choosing us! Your order has been confirmed.')
                return redirect(url_for('main.index'))
           except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

storeapp/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  <!-- Fonts -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Sofia|Trirong&effect=neon|outline|emboss|shadow-multiple">

  <title>Zoe's Fruit Garden</title>


  <style>
    html,
    body {
      height: 100%;
      margin: 0;
      padding: 0;
    }

    body {
      background-color: #7fad96;
    }


    .d-flex {
      display: flex !important;
      flex-direction: column !important;
    }

    .min-vh-100 {
      min-height: 100vh !important;
    }

    .flex-grow-1 {
      flex: 1 0 auto !important;
    }


    .navbar-fixed-top {
      position: fixed !important;
      top: 0;
      width: 100%;
      z-index: 9999;
    }


    main {
      margin-top: 80px;
    }
  </style>
</head>

<body>
  <div class="d-flex min-vh-100">

    <header class="navbar-fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light px-3" style="background-color: #9fcabc;">
        <div class="container-fluid" style="font-family:Trirong, sans-serif; font-size: 23px;">
          <a href="{{ url_for('main.order') }}" class="navbar-brand text-dark" style="font-size: 25px;">
            My Shopping Cart
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link text-dark" href="{{ url_for('main.index', _anchor='category_anchor') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark"
                  href="{{ url_for('main.index', _anchor='categories_anchor') }}">Categories</a>
              </li>
              <li class="nav-item pl-lg-5 pt-1">
                <form class="form-inline" action="{{ url_for('main.search') }}">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                    name="search"
                    style="background: transparent; border-color: #17a2b8; border-width: 2; font-size: 20px;">
                  <button class="btn btn-info" type="submit" style="width: 90px; font-size: 20px;">Search</button>
                </form>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>


    <main class="flex-grow-1">
      <div class="container">
        {% block main %}
        {% endblock %}
      </div>
    </main>


    <footer class="footer text-center justify-content-center align-self-center pt-2"
      style="width: 100%; background: linear-gradient(70deg, #9fcabc, 40%, #aed4c1); font-size: 23px; height: 50px;">
      <span class="text-dark">Zoe's Fruit Garden &copy; 2023</span>
    </footer>
  </div>

  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"></script>
</body>

</html>

storeapp/templates/checkout.html
{% extends 'base.html' %}

{% import 'bootstrap4/form.html' as wtf %}


{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-danger" role="alert" style="font-family: Trirong, sans-serif;">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endblock %}

{% block main %}
<style>
    .alert {
        margin-top: 190px;
        z-index: 1002;
    }

    @media (min-width: 992px) {
        .h1 {
            font-size: 60px;
        }

        p {
            font-size: 20px;
        }

        .form-label {
            font-size: 23px;
        }

        .btn {
            font-size: 23px;
            padding-inline: 15px;
        }

        .footer {
            font-size: 23px;
        }

    }

    @media (max-width: 991px) and (min-width: 767px) {

        .h1 {
            font-size: 40px;
        }

        p {
            font-size: 18px;
        }

        .form-label {
            font-size: 20px;
        }

        .btn {
            font-size: 20px;
            padding-inline: 13px;
        }

        .footer {
            font-size: 20px;
        }
    }

    @media (max-width: 765px) and (min-width: 576px) {

        .h1 {
            font-size: 40px;
        }

        p {
            font-size: 16px;
        }

        .form-label {
            font-size: 18px;
        }

        .btn {
            font-size: 18px;
            padding-inline: 10px;
        }

        .footer {
            font-size: 18px;
        }
    }

    @media (max-width: 575px) {
        .h1 {
            font-size: 30px;
        }

        p {
            font-size: 14px;
        }

        .form-label {
            font-size: 16px;
        }

        .btn {
            font-size: 13px;
            padding-inline: 9px;
        }

        .footer {
            font-size: 15px;
        }

        .footer {
            margin-top: 20px;
        }
    }
</style>


<section style="font-family: Trirong, sans-serif;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="h1 font-effect-shadow-multiple" style="font-family: Sofia, sans-serif; padding-top: 90px;">
                    Checkout</h1>
                <p>
                    Thank you for choosing us! Please provide your details below. Your fruit is coming to you soon!
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form method="POST" action="{{ url_for('main.checkout') }}">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.firstname.label(class="form-label") }}
                        {{ form.firstname(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.surname.label(class="form-label") }}
                        {{ form.surname(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-label") }}
                        {{ form.email(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.phone.label(class="form-label") }}
                        {{ form.phone(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.address.label(class="form-label") }}
                        {{ form.address(class="form-control") }}
                    </div>
                    <button type="submit" class="btn btn-info mr-4 mt-4">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

storeapp/templates/index.html
{% extends 'base.html' %}


{% block main %}
<style>
  @media (min-width: 992px) {
    .card-body {
      height: 700px;
    }

    .h1 {
      font-size: 60px;
    }

    .h2 {
      font-size: 37px;
    }

    .h3 {
      font-size: 30px;
    }

    .p {
      font-size: 24px;
    }

    .footer {
      font-size: 23px;
    }
  }

  @media (min-width: 992px) and (max-width: 1199px) {
    .card-body {
      height: 910px;
    }

    .h1 {
      font-size: 60px;
    }

    .h2 {
      font-size: 37px;
    }

    .h3 {
      font-size: 30px;
    }

    .p {
      font-size: 24px;
    }

    .footer {
      font-size: 23px;
    }

  }

  @media (max-width: 991px) and (min-width: 767px) {
    .card-body {
      height: 300px;
    }

    .card-section {
      margin-bottom: 30px;
    }

    .h1 {
      font-size: 40px;
    }

    .h2 {
      font-size: 28px;
    }

    .h3 {
      font-size: 25px;
    }

    .p {
      font-size: 20px;
    }

    .footer {
      font-size: 20px;
    }
  }

  @media (max-width: 765px) and (min-width: 576px) {
    .card-body {
      height: 400px;
    }

    .card-section {
      padding-bottom: 30px;
    }

    .h1 {
      font-size: 40px;
    }

    .h2 {
      font-size: 25px;
    }

    .h3 {
      font-size: 20px;
    }

    .p {
      font-size: 22px;
    }

    .footer {
      font-size: 18px;
    }
  }

  @media (max-width: 575px) {
    .card-section {
      padding-bottom: 20px;
    }

    .h1 {
      font-size: 30px;
    }

    .h2 {
      font-size: 20px;
    }

    .h3 {
      font-size: 14px;
    }

    .p {
      font-size: 14px;
    }

    .footer {
      font-size: 15px;
    }
  }
</style>
<!-- Carousel to display our fruit to users!-->
<div class="container">
  <div>
    <h1 class="h1 text-dark font-effect-shadow-multiple" style="font-family: Sofia, sans-serif; padding-top: 90px;">
      Gallery of our products</h1>
  </div>
  <br />
  <div id="carouselExampleCaptions" class="carousel slide pb-5" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
      <!-- Carousel item1 is citrus -->
      <div class="carousel-item active">
        <img src="https://images.pexels.com/photos/327098/pexels-photo-327098.jpeg" alt="Orange"
          style="height: 700px; object-fit: cover;" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5 style="font-family: Sofia, sans-serif; font-size: 32px;">Citrus</h5>
          <p style="font-family: Trirong, sans-serif; font-size: 22px;">Look at the citrus fruit, so fresh!</p>
        </div>
      </div>

      <!-- Carousel item2 is melons -->
      <div class="carousel-item">
        <img
          src="https://images.pexels.com/photos/7227503/pexels-photo-7227503.jpeg?cs=srgb&dl=pexels-polina-kovaleva-7227503.jpg"
          alt="Melons" style="height: 700px; object-fit: cover;" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5 style="font-family: Sofia, sans-serif; font-size: 32px;">Melons</h5>
          <p style="font-family: Trirong, sans-serif; font-size: 22px;">Try our juicy rockmelons and watermelons now!
          </p>
        </div>
      </div>

      <!-- Carousel item3 is berries -->
      <div class="carousel-item">
        <img src="https://images.pexels.com/photos/1269611/pexels-photo-1269611.jpeg" alt="Berries"
          style="height: 700px; object-fit: cover;" class="d-block w-100">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="text-dark" style="font-family: Sofia, sans-serif; font-size: 32px;">Berries</h5>
          <p class="text-dark" style="font-family: Trirong, sans-serif; font-size: 22px;">We have a variety of berries
            to choose: blueberry, strawberry, raspberry!</p>
        </div>
      </div>
    </div>

    <!-- "Previous" button-->
    <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>

    <!-- "Next" button-->
    <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
  </div>
</div>


<!-- marketing information -->
<section style="font-family:Trirong, sans-serif;">
  <div class="container">
    <div class="text-dark">
      <div>
        <p class="h1 text-dark mb-4 font-effect-shadow-multiple"
          style="font-family: Sofia, sans-serif; padding-top: 100px;">Why us?</p>
      </div>
    </div>

    <!-- CSS Grid -->
    <div class="row">
      <div class="col-md-12 text-center">
        <article>
          <h2 class="h2">Fresh fruits from local Farm!</h2>
          <h3 class="h3">We have the freshest and juicy fruits all around Australia!
            Our fruits are grown in our local farm, so you can be sure that they are fresh and delicious!
          </h3>
        </article>
      </div>

      <div class="row pt-5">
        <div class="col-6">
          <picture>
            <img src="{{url_for('static', filename='img/berryfromfarm.jpg')}}" class="img-fluid" alt="farm picture">
          </picture>
        </div>

        <div class="col-6">
          <picture>
            <img src="{{url_for('static', filename='img/citrusfromfarm.jpg')}}" class="img-fluid" alt="farm picture">
          </picture>
        </div>
      </div>
    </div>
</section>


<!-- display the categories to the user -->
<section class="container">
  <div class="text-dark">
    <div>
      <p class="h1 text-dark font-effect-shadow-multiple" id="categories_anchor"
        style="font-family: Sofia, sans-serif; padding-bottom: 20px; padding-top: 100px;">Choose what category you like!
      </p>
    </div>
  </div>
  <div class="card-deck" style="font-family:Trirong, sans-serif;">

    <div class="row">
      {% for category in category %}
      <div class="col-12 col-med-4 col-lg-4 card-section mb-5">
        <div class="card">
          <img class="card-img-top" src="{{ url_for('static', filename='img/'+ category.image)}}"
            alt="{{category.name}}" style="object-fit: cover; height: 420px;">
          <div class="card-body">
            <h3 class="card-title h2">{{category.name}}</h3>
            <p class="p card-text">{{category.description}}</p>
          </div>
          <div class="card-footer"><a href="{{url_for('main.category_fruits', categoryid=category.id)}}"
              class="btn btn-info" style="font-size: 23px; padding-inline: 15px;">Fruits</a></div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!-- jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

{% endblock %}

storeapp/templates/order.html
{% extends 'base.html' %}

{% block main %}
<style>
    @media (min-width: 992px) {
        .h1 {
            font-size: 60px;
        }

        .h2 {
            font-size: 37px;
        }

        .h3 {
            font-size: 30px;
        }

        .btn {
            font-size: 23px;
            padding-inline: 15px;
        }

        .btn-section {
            margin-bottom: 50px;
        }

        .footer {
            font-size: 23px;
        }

        .btn-section {
            flex-direction: row;
            justify-content: space-between;
            column-gap: 10px;
        }
    }

    @media (min-width: 992px) and (max-width: 1199px) {
        .h1 {
            font-size: 60px;
        }

        .h2 {
            font-size: 37px;
        }

        .h3 {
            font-size: 30px;
        }

        .btn {
            font-size: 23px;
            padding-inline: 15px;
        }

        .footer {
            font-size: 23px;
        }

        .btn-section {
            flex-direction: row;
            justify-content: space-between;
            column-gap: 10px;
        }

    }

    @media (max-width: 991px) and (min-width: 767px) {

        .h1 {
            font-size: 40px;
        }

        .h2 {
            font-size: 28px;
        }

        .h3 {
            font-size: 25px;
        }

        .btn {
            font-size: 20px;
            padding-inline: 13px;
        }

        .footer {
            font-size: 20px;
        }

        .btn-section {
            flex-direction: row;
            justify-content: space-between;
            column-gap: 10px;
        }
    }

    @media (max-width: 765px) and (min-width: 576px) {
        .h1 {
            font-size: 40px;
        }

        .h2 {
            font-size: 25px;
        }

        .h3 {
            font-size: 20px;
        }

        .btn-section.btn {
            font-size: 18px;
            margin-left: 20px;
        }

        .footer {
            font-size: 18px;
        }

        .btn-section {
            display: flex;
            flex-direction: column;
            row-gap: 6px;
        }
    }

    @media (max-width: 575px) {

        .h1 {
            font-size: 30px;
        }

        .h2 {
            font-size: 20px;
        }

        .h3 {
            font-size: 14px;
        }

        .btn {
            font-size: 14px;
            padding-inline: 9px;
        }


        .footer {
            font-size: 15px;
        }

        .card {
            margin-bottom: 6px;
        }

        .btn-section {
            flex-direction: column;
            justify-content: center;
            row-gap: 10px;
        }


    }

    .btn-section {
        display: flex;
        margin-bottom: 30px;
    }
</style>
<!-- display contents of user basket -->
<section style="font-family:Trirong, sans-serif;">
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3 class="h1 font-effect-shadow-multiple" style="font-family: Sofia, sans-serif; padding-top: 90px;">
                Shopping Cart</h3>
        </div>
        <!-- each fruit on separate row -->
        {% for fruit in order.fruit %}
        <div class="row shadow-md my-row mb-3">
            <div class="col-sm-10 card">
                <h2 class="h2 card-header">{{ fruit.name }}</h2>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <img class="img-thumbnail" src="{{ url_for('static', filename=('img/' + fruit.image)) }}">
                        </div>
                        <div class="col-10">
                            <!-- Item Description -->
                            <h3 class="h3 card-text">{{ fruit.description }}</h3>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <!-- right column has price and delete button -->
            <div class="col-sm-2">
                <!-- delete item button -->
                <h3 class="h3">{{ "$%.2f"|format(fruit.price) }}</h3>
                <form method="POST" action="{{ url_for('main.deleteorderitem') }}">
                    <input type="hidden" name="id" value="{{ fruit.id }}">
                    <input type="submit" value="Delete" class="btn btn-info mb-3">
                </form>
            </div>
        </div>
        {% endfor %}

        <!-- total price and page controls -->
        <section style="font-family: Trirong, sans-serif;">
            <div class="row co-12 d-flex">
                <h3 class="h3 mt-4">Total Price: {{ "$%.2f"|format(totalprice) }}</h3>
            </div>

            <div class="row btn-section co-12 mt-2 ">
                <a href="{{ url_for('main.index', _anchor='categories_anchor') }}" class="btn btn-info">Search
                    By Category</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-info">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-info">Empty Shopping Cart</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}